version: '3.0'

services:
  grafana:
    container_name: 'yandexcloud-yandexcloudlogging-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/yandexcloud-yandexcloudlogging-datasource
      - ./provisioning:/etc/grafana/provisioning
